# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3f49691ca3c075a668596b87debc6645ef7df950884f5924f97f6c9b4dfff7d44eb5654615fe381444f4fd7aea10d2f9791b1bef0dbf00b6190b9982763cad

test:
  secret_key_base: 6290e04c75817a1b868ffb2f7b2d1229bd3e4d340dcec5a4ea6ce08561ca1e6baedcdadc74bad6adca1021ce5aab1d2d08c59fa6ed868cc3aade437acd3c2f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
